server:
  error:
    include-message: always

spring:
  application:
    name: trello-project
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/trello
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'